bno08x_driver:
  ros__parameters:
    frame_id: imu_link

    i2c:
      enabled: true
      bus: /dev/i2c-7
      address: "0x4A"

    uart:
      enabled: false

    spi:
      enabled: false

    publish:
      magnetic_field:
        enabled: true
        rate: 50
      imu:
        enabled: true
        rate: 100
